### ISSUE TITLE
Bump Go v1.17

### ISSUE THREAD

**Issue by shogo82148** [kabesan/aws-sso-external#11]
> https://twitter.com/golang/status/1427378613289164810
> 
> 🎊 Go 1.17 is released!
> 
> 🗒️ Release notes: https://golang.org/doc/go1.17
> 
> 🚚 Download: https://golang.org/dl/#go1.17
> 
> #golang

**Comment by shmokmt** [comment]
＼( ‘ω’)／ウオオオオオアアアーーーッ！
